"""Added relationship between friends and Users and added new get_friends function

Revision ID: 15cc18cb935b
Revises: 938b175e1f8b
Create Date: 2025-05-14 07:36:16.861788

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '15cc18cb935b'
down_revision = '938b175e1f8b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('friends', schema=None) as batch_op:
        batch_op.create_foreign_key('fk_friends_user1_id_users', 'users', ['user2_id'], ['id'])
        batch_op.create_foreign_key('fk_friends_user2_id_users', 'users', ['user1_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('friends', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')

    # ### end Alembic commands ###
