"""Removed Drinks - Reviews Link to update reviews before populating drinks

Revision ID: 5795d52e14d9
Revises: 
Create Date: 2025-05-11 12:10:22.237629

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5795d52e14d9'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reviews', schema=None) as batch_op:
        batch_op.add_column(sa.Column('drink_name', sa.Text(), nullable=False))
        batch_op.drop_column('drink_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reviews', schema=None) as batch_op:
        batch_op.add_column(sa.Column('drink_id', sa.INTEGER(), nullable=True))
        batch_op.drop_column('drink_name')

    op.create_table('location_drink',
    sa.Column('drink_id', sa.INTEGER(), nullable=False),
    sa.Column('location_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['drink_id'], ['drinks.id'], ),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], ),
    sa.PrimaryKeyConstraint('drink_id', 'location_id')
    )
    # ### end Alembic commands ###
