"""changed private to is_private that is now a boolean type

Revision ID: 7208b818b2fb
Revises: 0c9d2f81287b
Create Date: 2025-05-12 09:01:55.010716

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7208b818b2fb'
down_revision = '0c9d2f81287b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reviews', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_private', sa.Boolean(), nullable=True))

        batch_op.drop_column('private')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reviews', schema=None) as batch_op:
        batch_op.add_column(sa.Column('private', sa.INTEGER(), server_default=sa.text("'1'"), nullable=True))
        batch_op.drop_column('is_private')

    # ### end Alembic commands ###
