"""Added Like Count to reviews

Revision ID: 8822dd6a7419
Revises: 7208b818b2fb
Create Date: 2025-05-12 11:46:15.602422

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8822dd6a7419'
down_revision = '7208b818b2fb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reviews', schema=None) as batch_op:
        batch_op.add_column(sa.Column('like_count', sa.Integer(), server_default='0', nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reviews', schema=None) as batch_op:
        batch_op.drop_column('like_count')

    # ### end Alembic commands ###
