"""Added Friends Table

Revision ID: 938b175e1f8b
Revises: 8822dd6a7419
Create Date: 2025-05-14 07:32:29.136932

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '938b175e1f8b'
down_revision = '8822dd6a7419'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reviews', schema=None) as batch_op:
        batch_op.drop_column('like_count')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reviews', schema=None) as batch_op:
        batch_op.add_column(sa.Column('like_count', sa.INTEGER(), server_default=sa.text("'0'"), nullable=True))

    # ### end Alembic commands ###
