"""Updated Reviews Model to better fit reviews that will be uploaded

Revision ID: e3b5e07e33ad
Revises: 5795d52e14d9
Create Date: 2025-05-11 14:05:33.012805

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e3b5e07e33ad'
down_revision = '5795d52e14d9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reviews', schema=None) as batch_op:
        batch_op.add_column(sa.Column('drink_size', sa.String(length=20), nullable=False))
        batch_op.alter_column('sugar_level',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
        batch_op.alter_column('ice_level',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reviews', schema=None) as batch_op:
        batch_op.alter_column('ice_level',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
        batch_op.alter_column('sugar_level',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
        batch_op.drop_column('drink_size')

    # ### end Alembic commands ###
